### ISSUE TITLE
2.0 Polymer.LegacyElement Ruleset

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-linter#13]

**Comment by rictic** [comment]
Created, but not filled out by #18

**Comment by rictic** [comment]
Filed issues for all of the rules we'll want for this ruleset and marked them as part of the 1.0.0 milestone, at which point we'll be able to deprecate polylint and remove it from the cli.

**Comment by justinfagnani** [comment]
Polymer.LegacyElement is no more. Closing this.
