### ISSUE TITLE
Wrap <style is="custom-style"> in <custom-style>

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-linter#155]
A hybrid rule / upgrade pass.

**Comment by stramel** [comment]
I'm going to try to pick this up next if it is still available.

**Comment by rictic** [comment]
> I'm going to try to pick this up next if it is still available.

Yep, it is! The important thing to note is that this should only apply to styles outside of dom-modules.

**Comment by stramel** [comment]
@rictic Agreed! This would be a cool one to have context aware rules. Like wrapping is great for hybrid but on P2 we could warn about/fix the extension and/or warn about missing element.

Hope to have a PR out in a day or two.
